services:
  cache:
    image: redis:7.0
    container_name: CNT-Cache
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - cache:/data

  dsapi:
    image: sflewis/datastore-service
    container_name: CNT-DSService
    depends_on: 
      - cache
    ports:
      - 9090:9090
    environment:
      HOST:
      PORT: 9090
      ACTIVEDRIVER: redis
      REDIS_TLS_URL: cache
      REDIS_URL: cache
      REDIS_PORT: 6379

  trivia-service:
    image: sflewis/trivia-service
    container_name: CNT-TriviaService
    depends_on: 
      - dsapi
    ports:
      - 8080:8080
    environment:
      HOST:
      PORT: 8080
      DS_NAME: http://dsapi
      DS_PORT: 9090

  web-client:
    image: sflewis/trivia-client
    container_name: CNT-WEBCLIENT
    depends_on: 
      - trivia-service
    ports:
      - 3000:3000
    environment:
      HOST:
      PORT: 3000
      TRIVIA_SERVICE_NAME: http://trivia-service
      TRIVIA_SERVICE_PORT: 8080

volumes:
  cache:
    driver: local